config/routes.rb
Rails.application.routes.draw do


  get 'rooms/show'
	devise_for :users
	root  'home#top'
	get 'favorites/index'
	get 'home/about' => "home#about"
	get 'users/follows'=>"users#follows"
	get 'users/follower'=>"users#follower"
	resources :users,only: [:show,:index,:edit,:update]

	resources :books, only: [:new,:create,:index,:show, :edit] do
		resource :favorites, only: [:create,:destroy]
		resources :book_comments, only: [:create,:destroy]
			collection do
			  get 'search'
			end
	end
	resources :relationships, only:[:create,:destroy]
	 resources :rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable,:validatable



  attachment :profile_image, destroy: false
  has_many :books,dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites

  enum  gender: { unknown: 0, male: 1}

  scope :get_by_name, ->(name) {
    where("name like ?", "%#{name}%")
  }
  scope :get_by_gender, ->(gender) {
    where(gender: gender)
  }


#いいね一覧＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
has_many :favorite_books,through: :favorites,source: :book
#================================================================


# userのbookがきえたら、同じく消えるdependentのコード
has_many :entries
has_many :direct_messages
has_many :rooms, through: :entries



# ↓フォロワーした　のつくりかた
# ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :relationships, foreign_key: 'user_id'
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :relationships, source: :follow
 # フォロー上relationships
 # ========================================================================================


# ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
 # フォロワーされてる下reverse_of_relationships
 has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
   # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
   has_many :followers, through: :reverse_of_relationships, source: :user
# =========================\==============================================================


# フォローする
def follow(other_user)
  unless self == other_user
    self.relationships.find_or_create_by(follow_id: other_user.id)
  end
end
# フォロー外す
def unfollow(other_user)
  relationship = self.relationships.find_by(follow_id: other_user.id)
  relationship.destroy if relationship
end
# フォロー確認# 現在のユーザーがフォローしてたらtrueを返す
def following?(other_user)
  self.followings.include?(other_user)
end
# ↑ここまでフォロー機能


  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence:true, length: {maximum: 20, minimum: 2}
  validates :introduction,length:{maximum:50}

  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])

    else
      User.all
    end
  end



  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

#検索機能
def index
  if params[:search].present?
    @users = User.where(name: params[:search])

    if params[:name].present?
      @users = @users.get_by_name params[:name]
    end
    if params[:gender].present?
      @users = @users.get_by_gender params[:gender]
    end

  else
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  end
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else

  		render :edit
  	end
  end
  # user.rbのhas_many :followings, through: :relationships, source: :follow
  def follows
    @users = current_user.followings
  end

  # user.rbの has_many :followers, through: :reverse_of_relationships, source: :user
  def follower
    @users = current_user.followers
  end
# user <%= form_for(@user) do |f| %>したときに３つのものしかもってこない(user_params)
private
def user_params
 params.require(:user).permit(:name, :introduction, :profile_image, :postcode, :prefecture_name, :address_city, :address_street, :address_building)
end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。他の人ユーザーに見られないようにする   ＝＝違ったら  3行目
  def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<td><%= link_to user.relationships.count,users_follows_path %>フォロー</td>
	</tr>
	<tr>
		<td><%= link_to user.reverse_of_relationships.count,users_follower_path%>フォロワー</td>
	</tr>
</table>
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>



<%= render 'relationships/follow_button' ,user: user  %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/follower.html.erb
 <div class="container">
 	<h1>Follow Userskkkkk</h1>

 	<table class="table">
 		<table class="table">
 			<thead>
 				<tr>
 					<th>image</th>
 					<th>name</th>
 					<th colspan="3"></th>
 				</tr>
 			</thead>

 			<% @users.each do |user| %>
 			<tbody>
 				<tr>
 					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
 					<td><%= user.name%></td>
 					<td><%= link_to user.relationships.count, users_follows_path %>followsフォロー</td>
 					<td><%= user.reverse_of_relationships.count %>followerフォロワー</td>
 					<td><%= render 'relationships/follow_button',user: user %></td>

 					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>

 					<% end %>

 				</tr>
 			</tbody>
 		</table>
 	</div>

app/views/users/follows.html.erb
 <div class="container">
 	<h1>Follow Users</h1>

 	<table class="table">
 		<thead>
 			<tr>
 				<th>image</th>
 				<th>name</th>
 				<th colspan="3"></th>
 			</tr>
 		</thead>

 		<% @users.each do |user| %>
 		<tbody>
 			<tr>
 				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
 				<td><%= user.name%></td>
 				<td><%= link_to user.relationships.count, users_follows_path %>followsフォローする</td>
 				<td><%= user.reverse_of_relationships.count %>followerフォロワーする</td>
 				<td><%= render 'relationships/follow_button',user: user %></td>

 				<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
 				<% end %>

 			</tr>
 		</tbody>
 	</table>
 </div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= form_with url:users_path,method: :get,data: {remote: false} do %>

			<%= text_field_tag :search %>
			<%= submit_tag "users検索", :name => nil %>
			<%end%>


			<div>
				<%= form_tag(users_path, method: "get") do %>
				<%= label_tag :name, "名前" %><%= text_field_tag :name, params[:name] %>
				<%= label_tag :name, "性別" %>
				<%= select_tag :gender, options_for_select(User.genders), include_blank: true %>
				<%= submit_tag "検索" %>
				<% end %>
			</div>


			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

			<% #User.each do |genre|%>
			<h5><%#= link_to genre, users_path(sex: sex) ,class:"btn btn-primary btn-xs"%></h5>
			<%#end%>
		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 60, 60, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>
						<td><%= link_to user.relationships.count, users_follows_path %>followsフォロー</td>
						<td><%= user.reverse_of_relationships.count %>followerフォロワー</td>
						<td><%= render 'relationships/follow_button',user: user %></td>

						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
						<div class="field">
							<td><%=user.sex_before_type_cast %></td>
							<td><%#=user.gender%></td>
							<% #user::sex.each do |genre|%>
							<td><%#= link_to genre, users_path(sex: sex) ,class:"btn btn-primary btn-xs"%></td>
							<%#end%>


						</div>
					</tr>
					<% end %>
				</tbody>
				<%= link_to :back do %>
				<button>戻る</button>
				<% end %>
			</table>
		</div>
	</div>
</div>
<!--users一覧 -->
<td>
	<!-- トップに戻る -->
	<span id="back">
		<a href="#">
			<img src="assets/arrow.png" alt="">
			<p>トップ</p>
		</a>
	</span>
	<!-- トップここまで -->

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
			<!--同コントローラーのviewで表示ならusersは省略可 -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>



		<% unless @user.id == current_user.id %>
		<% if @isRoom == true %>
		<%= link_to "チャットへ", room_path(@roomId) %>
		<% else %>
		<%= form_for @room do |f| %>
		<%= fields_for @entry do |e| %>
		<%= e.hidden_field :user_id, :value=> @user.id %>
		<% end %>
		<%= f.submit "チャットを始める" %>
		<% end %>
		<% end %>
		<% end %>

		<h2>Books</h2>
		<!--books一覧 -->
		<div class="col-xs-9">
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to (book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!--books一覧 -->