config/routes.rb
Rails.application.routes.draw do


  get 'rooms/show'
	devise_for :users
	root  'home#top'
	get 'favorites/index'
	get 'home/about' => "home#about"
	get 'users/follows'=>"users#follows"
	get 'users/follower'=>"users#follower"
	resources :users,only: [:show,:index,:edit,:update]

	resources :books, only: [:new,:create,:index,:show, :edit] do
		resource :favorites, only: [:create,:destroy]
		resources :book_comments, only: [:create,:destroy]
			collection do
			  get 'search'
			end
	end
	resources :relationships, only:[:create,:destroy]
	 resources :rooms
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites
	has_many :book_comments
	attachment :image

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	def self.search(search)
    if search
      Book.where(['title LIKE ?', "%#{search}%"])
    else
      Book.all
    end
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,only:[:edit]

  def show
  	@book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
    @book_comments = BookComment.new

  end

  def index
    if params[:search].present?
      @books = Book.where(title: params[:search])
    else
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end
    @book = Book.new

  end


  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
     #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit

  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。

      render "edit"
    end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

def search
  @books = Book.search(params[:search])
 
end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end
  def correct_user
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
	<%= link_to book_favorites_path(book_id: book), method: :delete, remote: true do %>
		<i class="glyphicon glyphicon-heart"></i>
		<%= book.favorites.count %>いいねする
	<% end %>
<% else %>
	<%= link_to book_favorites_path(book_id: book), method: :post, remote: true do %>
		<i class="glyphicon glyphicon-heart-empty"></i>
		<%= book.favorites.count %>いいねする
	<% end %>
<% end %>

app/views/books/_newform.html.erb
<% if book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
    	<p>%= book.errors.full_messages.count%> error</p>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :Opinion %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>
<input class="number" max="5.0" min="0" name="rate" step="0.5" type="number" placeholder="評価(５段階評価)"/>

	<div class="actions row">

		<%= f.submit 'komennto', class: "btn btn-success col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
	<% if @book.errors.any? %>
          <p><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
        <% @book.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
<% end %>

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<header>
	<div id="nav-drawer">
		<input id="nav-input" type="checkbox" class="nav-unshown">
		<label id="nav-open" for="nav-input"><span></span></label>
		<label class="nav-unshown" id="nav-close" for="nav-input"></label>
		<div id="nav-content">
			<%= form_with url:books_path,method: :get,data: {remote: false} do %>
			<%= text_field_tag :search %>
			<%= submit_tag "Title検索", :title => nil %>
			<%end%>

			<li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
			<li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
			<li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
			<li><%= link_to ' いいねした一覧', favorites_index_path ,class: "glyphicon glyphicon-heart"%></li>
			<li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
		</div>
	</div>
</header>


<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= form_with url:books_path,method: :get,data: {remote: false} do %>
			<%= text_field_tag :search %>
			<%= submit_tag "Title検索", :title => nil %>
			<%end%>

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books index</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
					<!--  -->
					<tbody>
						<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
								<% end %>
							</td>
							<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
							<td><%= book.body %></td>
							<td>
								<!--自分（ログインしているユーザ）が含まれているかをfavorited_by?メソッドで判定しています-->
								<td id="book_<%= book.id %>">
									<%= render 'favorite', book: book %></td>
								</div>
								<td> <a href="#comments">コメント数<%= book.book_comments.count %></td>
								</tr>
								<% end %>
							</tbody>
						</table>

						<!--books一覧 -->


					</div>
				</div>
			</div>
			<!-- トップに戻る -->
			<span id="back">
				<a href="#">
					<img src="assets/arrow.png" alt="">
				</a>
			</span>
			<!-- トップここまで -->

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3"> 
			<h2>User info</h2>
			<%= render 'users/profile',user:@user %>

			<h2>New book</h2>
			<%= render 'books/newform',book:@books%>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>



			<table class="table">
				<div id = "star-rate-<%= @book.id %>"></div>
				<script>
				  $('#star-rate-<%= @book.id %>').raty({
				    size: 36,
				    starOff:  '<%= asset_path('star-off.png') %>',
				    starOn : '<%= asset_path('star-on.png') %>',
				    starHalf: '<%= asset_path('star-half.png') %>',
				    half: true,
				    readOnly: true,
				    score: <%= @book.rate %>,
				  })
				</script>
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<% if current_user == @book.user%>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>

					<% end %>
					<td><i class="fa fa-comment"></i>
						<a href="#comments"><%= @book.book_comments.count %>コメント</a></td>
						<% @book.book_comments.each do |book_comment| %>
						<li class="comment">
							<div class="comment-body bb">
								<div class="comment-text">
									<div class="comment-author clearfix">
										<a href="#" class="link-author"><%= book_comment.user.name %></a>
										<a><td><%= book_comment.comment %></td>
											<% unless current_user != book_comment.user %>
											<td><%= link_to 'Destroy', book_book_comment_path(@book,book_comment), class: 'btn-sm btn-danger', method: :delete %></td>
											<% end %></a>
											<span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
										</span>
									</div>
									<div class="comment-entry"><%= book_comment.comment %></div>
								</div>
							</div>
						</li>
						<% end %>
					</tr>
				</table>
				<i class="fa fa-comment"></i>
				<a href="#comments"><%= @book.book_comments.count %>コメント</a>
				<div class="comment-list bt style-2" id="comments">
					<div class="float-wrapper">
						<h2 class="comment-count"><%= @book.book_comments.count %>件コメント</h2>
						<%= form_for [@book,@book_comments] do |f| %>
						<div class="row">
							<div class="col-sm-12">
								<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
							</div>
						</div>
						<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>