config/routes.rb
Rails.application.routes.draw do


  get 'rooms/show'
	devise_for :users
	root  'home#top'
	get 'favorites/index'
	get 'home/about' => "home#about"
	get 'users/follows'=>"users#follows"
	get 'users/follower'=>"users#follower"
	resources :users,only: [:show,:index,:edit,:update]

	resources :books, only: [:new,:create,:index,:show, :edit] do
		resource :favorites, only: [:create,:destroy]
		resources :book_comments, only: [:create,:destroy]
			collection do
			  get 'search'
			end
	end
	resources :relationships, only:[:create,:destroy]
	 resources :rooms
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2 -debug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <header class=>
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <!-- navbar-left 左寄せ　　　　　　navbar-right右寄せ　-->
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>


            
            <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' いいね', favorites_index_path ,class: "glyphicon glyphicon-heart"%></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about',home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign up' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <%= yield %>
    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

    </div>
  </body>
</html>